bind_addr: ":4443"

frontends:

  server1:
    backends:
      -
        addr: "192.168.1.1:443"

  server2:
    tls_key: server.key
    tls_crt: server.crt
    backends:
      -
        addr: "192.168.1.2:80"
